CREATE TABLE [dbo].[Posts]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[AuthorId] UNIQUEIDENTIFIER NOT NULL,
	[PostDate] DATETIME NOT NULL,
	[Topic] NVARCHAR(100) NOT NULL,
	[Body] NVARCHAR(100) NOT NULL,
	[Author] NVARCHAR(100) NOT NULL
)
